---
title: "data wrangling and plots"
author: "Maggie Slein"
date: "3/8/21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE, results = 'hide', message=FALSE}
## loading libraries 
pacman::p_load(metafor, tidyverse, viridis, ggsci, wesanderson)
#devtools::install_github("itchyshin/orchard_plot", subdir = "orchaRd", force = TRUE,build_vignettes = TRUE)
#library(orchaRd)

#load data
dat_MA_0<- read_csv("metafor.csv")
```


```{r, echo= FALSE, results = 'hide', message=FALSE}
##wrangling calculations for metafor

#make standardized SD columns based on N and SE vs SD
dat_MA <-dat_MA_0 %>% 
  mutate ( SD_constant= if_else ( variance_type== 0, constant_variance * sqrt(constant_samp), constant_variance))  %>%
  mutate ( SD_variable= if_else ( variance_type== 0, flux_variance * sqrt(flux_variance) , flux_variance)) 
         
#calculate ES for data
dat_MA_ES <-escalc(measure="SMD", m1i=constant_resp, m2i=flux_resp, 
            sd1i=`SD_constant`, sd2i= `SD_variable`, n1i=constant_samp, n2i=flux_samp, 
            data=dat_MA, slab=paste(study_id, experiment_id, response_id, sep=", ")) 

# Note in the above, you loose ~15% of data because of missing sample sizes and SEs reported, below these are removed for now
dat_MA_ES<-dat_MA_ES %>% 
  filter (!is.na(yi)) %>%
  filter(resp_units != "C") %>%
  filter(study_id != "piccau2017")
```

```{r, echo= FALSE, results = 'hide', message=FALSE}
## data wrangling for plots
#count and propotions for the different variables
count(dat_MA_ES, flux_range) #46 rows w/ range of 10, 51 w/ range of 15, 36 w/range of 6
count(dat_MA_ES, resp_units, sort = TRUE) 
count(dat_MA_ES, mean_temp_constant, study_id) #24 C common accross 5 studies
count(dat_MA_ES, resp_def, sort = TRUE) # body mass, avg. cum. num of eggs laid/fm, avg. num of eggs laid/fm, survival, rate of change, are the the most common reponses
count(dat_MA_ES, genus, study_id) # 3 studies featuring drosophila
count(dat_MA_ES, genus, species)# 16 genuses to bin by 
count(dat_MA_ES, size)# good spread for body size
count(dat_MA_ES, larger_group) # pretty much mostly animal studies


#removing outlier point to get better picture of data structure AND excluding CT assays 
normalized <- dat_MA_ES %>%
  filter(yi > -20) 
#filtering for studies with common variable g 
common_unit_g <-dat_MA_ES %>% 
filter(resp_def == "body mass")
#filtering for genus to only be drosophila 
drosophila <- dat_MA_ES %>% 
  filter(genus == "Drosophila")
#filtering for just flux ranges of 10 C 
common_range <- dat_MA_ES %>% 
  filter(flux_range == "10")
#filtering for just studies with mean temp of 24
common_temp <- dat_MA_ES %>% 
  filter(mean_temp_constant == "24")
```

# Plots 

## Question: How does response vary with study covariates?

```{r}
full_rf_model<-rma.mv(yi, vi, data=dat_MA_ES, mods = ~flux_range +
                        exp_age + size + org_level + mean_temp_constant, 
               random = ~1 | experiment_id/ study_id/ response_id,
                 method="REML") 
full_rf_model
```

## Relevant plots
### Figure 1.
```{r}
# boxplots of how fluctuation range influences SMD
ggplot(normalized, aes(x=flux_range, y=yi))+
  geom_point(alpha = 0.5)+
  theme_bw()+
  geom_smooth(method="lm", formula = y~x)+
  ggtitle("SMD across flux_range")
```

### Figure 2.
```{r}
# scatterplot of standardized mean response vs flux range colored and lm fit by org level
ggplot(normalized, aes(x=flux_range, y=yi, color = as.factor(org_level)))+
  geom_point()+
  geom_smooth(method="lm", formula = y~x)+
  ggtitle("SMD across fluctuation ranges colored by organization level 
          and fit with linear model")
```

### Figure 3. 
```{r}
#boxplot of SMD across levels of organization
ggplot(normalized, aes(x=as.factor(org_level), y=yi, fill=as.factor(org_level)))+
  geom_boxplot(alpha =0.7)+
  geom_point(alpha = 0.3)+
  scale_fill_tron()+
  theme_bw()+
  theme(legend.position = "bottom")+
  ggtitle("SMD across organization level")
```

### Figure 4.
```{r}
#scatterplot of standardized mean difference across flux range colored by study fit with lm 
ggplot(normalized, aes(x=flux_range, y=yi, color = study_id))+
  geom_point()+
  geom_smooth(method="lm", formula = y~x)+
  theme_minimal()+
  ggtitle("SMD across fluctuation ranges colored by 
          studies and fit with linear model by study")
```

## Question: How does response compare across studies and experiments?
```{r, message=FALSE}
#corresponding random effects model 
fig1 <- rma.mv(yi, vi, data=dat_MA_ES, 
               random = ~1 | experiment_id/ study_id,
                 method="REML") 
fig1
#trying out mixed effects model 
fig1me <- rma(yi, vi, data=dat_MA_ES, mods = ~study_id,
                 method="FE")
fig1me
```

## Relevant Plots 
### Figure 5.
```{r}
#SMD across all studies
ggplot(normalized, aes(x=reorder(study_id, -yi), y=yi, color = as.factor(experiment_id)))+
  geom_boxplot()+
  scale_color_tron()+
  theme_minimal()+
  theme(axis.text.x = element_text(face = "bold", 
                                   size = 10, angle = 45,hjust = 1), 
        legend.position = "bottom")+
  ggtitle("SMD across all studies")
```

### Figure 6. 
```{r, echo= FALSE}
# scatterplot of standardized mean response faceted by exp age
ggplot(normalized, aes(x=vi, y=yi, color = study_id))+
  geom_point()+
  theme_bw()+
  ggtitle("SMD across variance 
          colored by study")
```

### Figure 7.
```{r}
#looking at yi across studies with the same temperature range (10 C)
ggplot(common_range, aes(y=yi, x=reorder(study_id, -yi), color = study_id))+
  geom_boxplot()+
  geom_point(alpha = 0.5)+
  theme_minimal()+
  theme(axis.text.x = element_text(face = "bold", 
                                  size = 7, angle = 45))+
                                  ggtitle("SMD across studies with the same 
                                          temperature fluctuation range (10 C)")
```

### Figure 8.
```{r}
# scatterplot of how mean temperature influences SMD
ggplot(normalized, aes(x=mean_temp_constant, y=yi, color = study_id))+
  geom_point()+
  theme_bw()+
  ggtitle("SMD across mean temperature")
```


_________________________________
Supplementary Plots/Code

```{r, echo= FALSE, results = 'hide', message=FALSE, fig.show='hide'}

#looking at yi across studies with the same mean temperature (24 C)
ggplot(common_temp, aes(y=yi, x=reorder(study_id, -yi), color = study_id))+
  geom_point()+
  geom_boxplot()+
  theme_minimal()+
  theme(axis.text.x = element_text(face = "bold", 
                                   size = 7, angle = 45))+
  ggtitle("SMD across studies with the same mean temperature (24 C)")
#random effects model within subset data
fig13 <- rma.mv(yi, vi, data=common_temp,
               random = ~1 | experiment_id/ study_id,
                 method="REML") 
fig13
#simple linear model looking at how flux_range affects yi within subset data
simple13<-lm(yi~mean_temp_constant, data =common_temp)
summary(simple13)
```

```{r, echo= FALSE, results = 'hide', message=FALSE, fig.show='hide'}
#boxplots of SMD across different genuses colored by body size
ggplot(normalized, aes(y=yi, x= reorder(genus, -yi), color = as.factor(size)))+
  geom_point()+
  theme_minimal()+
  ggtitle("SMD across genuses colored by body size")+
  theme(axis.text.x = element_text(face = "bold", 
                                   size = 10, angle = 45,hjust = 1), 
        legend.position = "bottom")
#random effects model including genus as a random variable
fig11 <- rma.mv(yi, vi, data=dat_MA_ES, mods = ~size,
               random = ~1 | experiment_id/ study_id,
                 method="REML") 
fig11
#simple linear model looking at how genus affects yi
simple11<-lm(yi~genus, data =dat_MA_ES)
summary(simple11)
```

```{r, echo= FALSE, results = 'hide', message=FALSE, fig.show='hide'}
#trying to look at drosophila response across studies 
ggplot(drosophila, aes(y=yi, x=as.factor(flux_range), color = study_id))+
  geom_boxplot()+
  geom_point()+
  scale_color_tron()+
  theme_bw()+
  ggtitle("SMD across studies with the same study genus (Drosophila)")
#random effects model including org_level as a random variable
fig10 <- rma.mv(yi, vi, data=drosophila, mods = ~flux_range + study_id,
               random = ~1 | experiment_id/ study_id,
                 method="REML") 
fig10
#simple linear model looking at how flux_range and study_id affect yi in drosphila specific studies
simple10<-lm(yi~flux_range + study_id, data =drosophila)
summary(simple10)
```

```{r, echo= FALSE, results = 'hide', message=FALSE}
#random effects model including org_level as a random variable
fig6 <- rma.mv(yi, vi, data=dat_MA_ES, mods = ~mean_temp_constant,
               random = ~1 | experiment_id/ study_id,
                 method="REML") 
fig6
#simple linear model looking at how mean_temp_constant affects yi
simple6<-lm(yi~mean_temp_constant, data =dat_MA_ES)
summary(simple6)
```

```{r, echo= FALSE, results = 'hide', message=FALSE}
#basic linear model for study_id
simple1<-lm(yi ~ study_id, data = dat_MA_ES)
summary(fig1)
#basic linear model looking at how vi interacts with yi
simple2<-lm(yi ~ vi, data = dat_MA_ES)
summary(simple2)
```

```{r, echo= FALSE, results = 'hide', message=FALSE, fig.show='hide'}
#boxplot of experimental ages and how their yi's stack up 
ggplot(normalized, aes(x=exp_age, y=yi, color = as.factor(exp_age)))+
  geom_boxplot()+
  theme_bw()+
  ggtitle("SMD across different experimental ages")

#random effects model including exp_age as a random variable
fig3 <- rma.mv(yi, vi, data=dat_MA_ES, mods = ~exp_age, 
               random = ~1 | experiment_id/ study_id,
                 method="REML") 
fig3
#simple linear model looking at how exp_age affects yi
simple3<-lm(yi~exp_age, data =dat_MA_ES)
summary(simple3)
```

```{r, echo= FALSE, results = 'hide', message=FALSE, fig.show='hide'}
#boxplot of different experimental ages and how they vi's stack up 
ggplot(normalized, aes(x=exp_age, y=vi, color = as.factor(exp_age)))+
  geom_boxplot()+
  theme_bw()+
  ggtitle("Variance across different experimental ages")

count(normalized, exp_age)

#simple linear model looking at how exp_age affects vi
simple4<-lm(vi~ exp_age, data =dat_MA_ES)
summary(simple4)
```

```{r, echo= FALSE, results = 'hide', message=FALSE}
#random effects model including org_level as a random variable
fig5 <- rma.mv(yi, vi, data=dat_MA_ES, mods = ~org_level,
               random = ~1 | experiment_id/ study_id,
                 method="REML") 
fig5
#simple linear model looking at how org_level affects yi
simple5<-lm(yi~org_level, data =dat_MA_ES)
summary(simple5)
```

```{r, echo= FALSE, results = 'hide', message=FALSE}
#full random effects model looking at all the responses in the entire dataset
response_variable_mod <- rma.mv(yi, vi, data=dat_MA_ES, mods = ~resp_def, 
               random = ~1 | experiment_id/ study_id/ response_id,
                 method="REML") 
response_variable_mod

#full random effects model looking at all the response units in the entire dataset
response_units_mod <- rma.mv(yi, vi, data=dat_MA_ES, mods = ~resp_units, 
               random = ~1 | experiment_id/ study_id /response_id,
                 method="REML") 
response_units_mod
```

```{r, echo= FALSE, results = 'hide', message=FALSE}
#random effects model within subset data
fig12 <- rma.mv(yi, vi, data=common_range,
               random = ~1 | experiment_id/ study_id,
                 method="REML") 
fig12
#simple linear model looking at how flux_range affects yi within subset data
simple12<-lm(yi~flux_range, data =common_range)
summary(simple12)
```

```{r, echo= FALSE, results = 'hide', message=FALSE}
#random effects model including org_level as a random variable
fig9 <- rma.mv(yi, vi, data=dat_MA_ES, mods = ~flux_range + study_id,
               random = ~1 | experiment_id/ study_id,
                 method="REML") 
fig9
#simple linear model looking at how flux_range and study_id affect yi
simple9<-lm(yi~flux_range*study_id, data =dat_MA_ES)
summary(simple9)
```

```{r, echo= FALSE, results = 'hide', message=FALSE}
#random effects model including org_level as a random variable
fig8 <- rma.mv(yi, vi, data=dat_MA_ES, mods = ~flux_range + org_level,
               random = ~1 | experiment_id/ study_id,
                 method="REML") 
fig8
#simple linear model looking at how flux_range and org_level affect yi
simple8<-lm(yi~flux_range*org_level, data =dat_MA_ES)
summary(simple8)
```

```{r, echo= FALSE, results = 'hide', message=FALSE}
#random effects model including org_level as a random variable
fig7 <- rma.mv(yi, vi, data=dat_MA_ES, mods = ~flux_range,
               random = ~1 | experiment_id/ study_id,
                 method="REML") 
fig7 
#simple linear model looking at how flux_range affects yi
simple7<-lm(yi~flux_range, data =dat_MA_ES)
summary(simple7)
```

```{r, echo= FALSE, results = 'hide', message=FALSE, fig.show='hide'}
rf_model<-rma.mv(abs(yi), vi, data=dat_MA_ES, mods = ~flux_range +
                        exp_age + size + org_level + mean_temp_constant, 
               random = ~1 | experiment_id/ study_id/ response_id,
                 method="REML")
rf_model
```

```{r, echo= FALSE, results = 'hide', message=FALSE, fig.show='hide'}
#plot across studies with common response variable body mass
ggplot(common_unit_g, aes(y=yi, color=as.factor(flux_range), x = study_id))+
  geom_boxplot()+
  theme_minimal()+
  theme(axis.text.x = element_text(face = "bold", 
                                  size = 7, angle = 45))+
  ggtitle("SMD across fluctuation ranges colored by studies with the common unit grams")
#random effects model within subset data
fig14 <- rma.mv(yi, vi, data=common_unit_g,
               random = ~1 | experiment_id/ study_id,
                 method="REML") 
fig14
#simple linear model looking at how flux_range affects yi within subset data
simple14<-lm(yi~study_id, data =common_unit_g)
summary(simple14)
```



