# Conclusions and Future Directions {-}

While there are limitations to the reach of this meta-analysis and its results, it is the first cross-taxa quantitative summary of how environmental variability has been studied in the literature. Our results suggest that thermal variability influences responses across several studies, positively as lower mean temperatures with higher fluctuation ranges, and less so at high mean temperatures with lower fluctuation ranges.

However, most importantly, our results highlight the importance of learning from previous research to push how environmental variability is studied further. It has been noted for years the importance of including thermal variability in ecological research, yet there are still an overwhelming number of studies that employ the same patterns of variability with the same lack of reference to thermal performance. Going forward, experiments that explicitly account for and justify variation patterns with respect to generation time, organization level, duration, and relevance to natural conditions are needed. In order to draw conclusions that are relevant to natural conditions, patterns of variability across colors of noise (red, white, etc.) and across lengths of time must be investigated. A larger sample size of studies to draw more robust conclusions with respect to support for or against allometric scaling and MTE with respect to thermal variability would be useful. There is more to be studied on how additional experimental designs, e.g. acclimation or heat-wave simulations, as well as how biological performance responds to environmental variability. However, this is an important first step in quantitatively summarizing progress so far. 


